# Generated by Django 5.0.1 on 2024-01-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studnetID',
            new_name='studentID',
        ),
    ]
